"""Add explanation column to claims table.

Each Claim now carries two text fields: `text` (the statement with citations,
validated by the 3-layer validator) and `explanation` (plain-language detail
generated by the Composer, not validated, intended for the frontend report).

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-29
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_UP = "ALTER TABLE claims ADD COLUMN explanation TEXT NOT NULL DEFAULT '';"
_DOWN = "ALTER TABLE claims DROP COLUMN explanation;"


def upgrade() -> None:
    op.execute(_UP)


def downgrade() -> None:
    op.execute(_DOWN)
